# Generated by Django 4.1.5 on 2023-03-07 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0018_auto_20220910_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 21, 16, 16, 953133), help_text='Date the book is due to'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book_number',
            field=models.PositiveIntegerField(help_text='Book number for books of the save kind', null=True),
        ),
    ]
