# Generated by Django 4.1.5 on 2023-04-20 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0019_alter_book_issue_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 20, 26, 872257), help_text='Date the book is due to'),
        ),
    ]
